import sys
import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

logger = logging.getLogger("main")

try:
    from app.routes import auth, portfolio, trades, prices, leaderboard, documents
except Exception:
    # If any route module fails to import (bad config, missing dependency,
    # circular import), fail loudly and immediately instead of leaving
    # uvicorn to die silently with no visible reason in the logs.
    logger.exception("FATAL: failed to import route modules during startup")
    sys.stdout.flush()
    sys.stderr.flush()
    sys.exit(1)

app = FastAPI(title="Bullpen", version="1.0.0") # Entry point for the API

# Allows the static frontend (served from file:// or a separate dev server)
# to call the API with the X-Session-Id header.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# To run the API, use the command:
# uvicorn app.main:app --reload 
# /docs will have the interactive API documentation generated by FastAPI, allowing you to test the endpoints directly from the browser.

# Include the routers for different API endpoints
# Each router is prefixed with its respective path and tagged for documentation purposes
# Decoupling the routes into separate modules allows for better organization and maintainability of the codebase
app.include_router(auth.router)
app.include_router(portfolio.router)
app.include_router(trades.router)
app.include_router(prices.router)
app.include_router(leaderboard.router)
app.include_router(documents.router)

@app.get("/")
async def root():
    return {"message": "Bullpen Portfolio Intelligence API"}

