from fastapi import FastAPI
from app.routes import auth, portfolio, trades, prices, leaderboard, documents

app = FastAPI() # Entry point for the API

# To run the API, use the command:
# uvicorn app.main:app --reload 
# /docs will have the interactive API documentation generated by FastAPI, allowing you to test the endpoints directly from the browser.

# Include the routers for different API endpoints
# Each router is prefixed with its respective path and tagged for documentation purposes
# Decoupling the routes into separate modules allows for better organization and maintainability of the codebase
app.include_router(auth.router)
app.include_router(portfolio.router)
app.include_router(trades.router)
app.include_router(prices.router)
app.include_router(leaderboard.router)
app.include_router(documents.router)

@app.get("/")
async def root():
    return {"message": "Bullpen Portfolio Intelligence API"}

