from fastapi import FastAPI
from app.routes import auth, portfolio, trades, prices

app = FastAPI() # Entry point for the API

# To run the API, use the command:
# uvicorn app.main:app --reload 
# /docs will have the interactive API documentation generated by FastAPI, allowing you to test the endpoints directly from the browser.

# Include the routers for different API endpoints
# Each router is prefixed with its respective path and tagged for documentation purposes
# Decoupling the routes into separate modules allows for better organization and maintainability of the codebase
app.include_router(auth.router, prefix="/auth", tags=["auth"])
app.include_router(portfolio.router, prefix="/portfolio", tags=["portfolio"])
app.include_router(trades.router, prefix="/trades", tags=["trades"])
app.include_router(prices.router, prefix="/prices", tags=["prices"])



@app.get("/")
async def root():
    return {"message": "Welcome to the Crypto Trading Bot API!"}

